baseURL = 'https://g4s8.github.io/openbots'
languageCode = 'en-us'
title = 'OpenBots documentation'

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "blue"
