// Code generated by "stringer -type=TriggerType"; DO NOT EDIT.

package spec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TriggerTypeMessage-1]
	_ = x[TriggerTypeCallback-2]
	_ = x[TriggerTypeContext-3]
	_ = x[TriggerTypePreCheckout-4]
	_ = x[TriggerTypePostCheckout-5]
	_ = x[TriggerTypeState-6]
	_ = x[TriggerTypeFallback-7]
}

const _TriggerType_name = "TriggerTypeMessageTriggerTypeCallbackTriggerTypeContextTriggerTypePreCheckoutTriggerTypePostCheckoutTriggerTypeStateTriggerTypeFallback"

var _TriggerType_index = [...]uint8{0, 18, 37, 55, 77, 100, 116, 135}

func (i TriggerType) String() string {
	i -= 1
	if i >= TriggerType(len(_TriggerType_index)-1) {
		return "TriggerType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TriggerType_name[_TriggerType_index[i]:_TriggerType_index[i+1]]
}
