name: Docker build and push

on:
  push:
    branches: [ "master" ]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make DOCKER_TAG=latest docker
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Publish to Docker Hub
      run: docker push g4s8/openbots:latest
